version: '3.9'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "3000:3000"
    env_file:
      - .env

  chat-api:
    build:
      context: .
      dockerfile: Dockerfile.chat
    ports:
      - "4000:4000"
    env_file:
      - .env
